name: BACKEND

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version required by your Next.js app

      - name: Install dependencies
        run: npm install  # or yarn install if you are using Yarn

      - name: Run tests
        run: npm test  # or yarn test if you are using Yarn

      - name: Upload test results
        if: always()  # Ensures that results are uploaded even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.xml  # Adjust this path based on your test reporting setup
