name: FRONTEND

on:
  push:
    branches:
      - main
      - '**/feature/**' # Run on feature branches
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test -- --watchAll=false # Adjust if necessary

      - name: Run backend tests
        run: npm run test:api -- --watchAll=false # Adjust if necessary
