name: SonarQube analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  pull-requests: read
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: |
            -Dsonar.projectKey=POLO-SOEN341_POLO-SOEN341_Project_F24
            -Dsonar.organization=polo-soen341
            -Dsonar.sources="Sprint_4/App"
            -Dsonar.tests=tests
            -Dsonar.verbose=true
            -X
