name: SonarQube analysis
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  pull-requests: read
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarScanner with Java 17
        uses: docker://sonarsource/sonar-scanner-cli:4.8.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: |
            -Dsonar.projectKey=POLO-SOEN341_POLO-SOEN341_Project_F24
            -Dsonar.organization=polo-soen341
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.verbose=true
            -X
